### ISSUE TITLE
Consider migrating yours bash scripts to SparrowHub

### ISSUE THREAD

**Issue by melezhik** [TruboXL/bash-auto#1]
Hi , @TruboXL , I have checked your repo and would suggest you to migrate your scripts to https://sparrowhub.org - a automation scripts repository. A benefits you will gain: 

* scripts could be packaged, versioned and distributed in the same way as many convention packages manager do - like apt , yum , cpan,  ruby gems, etc.

* a scripts configuration is provided out of the box with some well known formats - yaml, json, Config::general , command line parameters , etc. 

* scripts documentation support - markdown , common line ( like a Linux man ) , web interface for browsering documentation, links to github source code , etc.

* scripts authority provided by account at sparrowhub , so scripts users understand clearly who is script maintainer and who address the issues to.

For examples of existed scripts - take a look at http://sparrowhub.org , let me know and I help on migration process.

ps. If it does not sound interesting, just close the issue.

---

Thanks . Alexey Melezhik , the author of sparrowhub.

**Comment by TruboXL** [comment]
Sorry @melezhik 
This repo is more of a personal sort of collection of mashed up amateur scripts, if you know what I mean :(

Doesn't seem to be a good fit to be hosted on your professional site...
Anyway, thanks for your suggestion. :)

**Comment by melezhik** [comment]
That's ok , @TruboXL   I see what you mean, before making a final decision please read my latest post on using sparrow and users scripts - http://blogs.perl.org/users/melezhik/2016/10/sparrow-remote-tasks---way-to-package-your-scripts-and-configurations.html , to make this even easier I would suggest to start using sparrow with some new scripts and see the benefits :-)
